apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: app
  DB_PASSWORD: {{ required "db.password is required" .Values.db.password }}