server:
  persistentVolume:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.local
    paths:
      - /
    pathType: Prefix
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - my-cluster-worker3

alertmanager:
  enabled: false
pushgateway:
  enabled: false
nodeExporter:
  enabled: true
kube-state-metrics:
  enabled: true

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'spring-boot-pods'
        metrics_path: '/actuator/prometheus'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - demo-app
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: (order-service|product-service|notification-service|api-gateway)
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: application
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: ${1}:8082
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_ip]
            target_label: __address__
            regex: 'order-service;(.*)'
            replacement: ${1}:8082
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_ip]
            target_label: __address__
            regex: 'product-service;(.*)'
            replacement: ${1}:8081
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_ip]
            target_label: __address__
            regex: 'api-gateway;(.*)'
            replacement: ${1}:8080
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_ip]
            target_label: __address__
            regex: 'notification-service;(.*)'
            replacement: ${1}:8083
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod