community:
  enabled: true

replicaCount: 1

monitoringPasscode: "admin1234"

service:
  type: ClusterIP

resources:
  requests:
    cpu: 400m
    memory: 1Gi
  limits:
    cpu: 800m
    memory: 2Gi

persistence:
  enabled: true
  size: 5Gi

postgresql:
  enabled: true
  primary:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

sonarProperties:
  sonar.forceAuthentication: "false"