spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092}

  mail:
    host: ${MAIL_HOST:mailhog.mailhog.svc.cluster.local}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

kafka:
  topics:
    order-events: order-events

notification:
  mail:
    from: noreply@demo-app.local

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info