replicaCount: 2

image:
  repository: ghcr.io/kevin-fechner/k8s-demo-app/frontend
  pullPolicy: IfNotPresent
  tag: "sha-fe1949d"

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  API_URL: http://api-gateway.demo-app.svc.cluster.local

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

readinessProbe:
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  path: /
  initialDelaySeconds: 20
  periodSeconds: 30